name: coronapass
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  qr_code_scanner: ^0.5.2
  permission_handler: ^8.1.4+2


  cupertino_icons: ^1.0.2
  dart_base45: ^1.0.1
  cbor: ^4.1.0
  json_serializable: ^5.0.1
  json_annotation: ^4.1.0
  qr_flutter:
    path: ./qr.flutter
  qr:
    path: qr.dart
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.0-beta.5
  rxdart: ^0.27.2
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  intl_utils: ^2.4.1
  flutter_localized_locales: ^2.0.3
  wakelock: ^0.5.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  build_runner: ^2.1.2

flutter:

  uses-material-design: true
  assets:
    - ehn-dcc-schema/valuesets/
    - assets/
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/FiraSans-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700



flutter_intl:
  enabled: true